### ISSUE TITLE
ChannelForbidden object has no attribute 'verified'

### ISSUE THREAD

**Issue by atrdev-rgb** [AmanoTeam/hydrogram#42]
AttributeError
'ChannelForbidden' object has no attribute 'verified'
  File "D:\Project\Telegram\Hydrogram\main.py", line 57, in main
    async for message in app.get_chat_history(chat_id=chat_id):
  File "D:\Project\Telegram\Hydrogram\main.py", line 122, in <module>
    asyncio.run(main(phone_number))
AttributeError: 'ChannelForbidden' object has no attribute 'verified'

**Comment by 2ei** [comment]
@atrdev-rgb better to open discussion here https://github.com/orgs/hydrogram/discussions

because it’s not issue
